### ISSUE TITLE
State-of-the-art in Typescript world

### ISSUE THREAD

**Issue by tomitrescak** [alm-tools/alm-tools.github.io#2]
@basarat will you consider to publish the very cool stuff you did here also for Atom? I always try to change to something else, but I have all the workflow and tool chain working in Atom, so it is quite difficult to chain to anything else. I would not even mind to pay premium price to get the support and updates just like Wallaby does. To summarise my experience:
1. Sublime - Supported by Microsoft, but quite dodgy experience, errors appear only in console, no nice dedicated pane such as Linter with TSLint in Atom. No help with import path statements.
2. VS Code - Still has a long way to go. Errors appear and disappear, require to rebuild the whole application. Missing tabs, missing dedicated error panes. No help on import paths, slow compilation. Positive - Uses pure tsc to compile the project, so you get latest features during compilation and error detection.
3. VS Community 2015 - Looks quite nice, but on MAC and Linux you need to run it in VM. Also it's quite slow on compilation side. Projects need to be run as Typescript HTML with obj and bin created. But, has everything one need.
4. ALM Tools, looks very nice and has quiet a lot of features. But it's proprietary editor missing all the goodies from the editors such as inclusion of test tools such as Wallaby JS, Minimap, Linting .. parallel support for multiple programming languages and their transpiration (CSSx, JSX ...)
5. Atom - Till now it is the best there is for typescript, yet the support is falling behind to bring in the latest in Typescript. You put so much love in this project and it can be seen. Will you consider creating a "Premium" package?

**Comment by basarat** [comment]
@tomitrescak I've given it a lot of thought and thanks again for your support and love :heart:. However I'm trying to create a cohesive experience and the only two options I see are completely highjacking the users editor (e.g. atom would no longer feel like atom and you might just end up disabling the plugin because it does too much) or creating my own (which is the path I am going down) :rose:
