### ISSUE TITLE
When I use QuickFix Import File, the Path is always lowercase.

### ISSUE THREAD

**Issue by nerothe** [alm-tools/alm-tools.github.io#3]
So if i have a File _"../TestTest.js"_ and i want to get the class _"Test"_ from it then it should be:
`import { Test } from "../TestTest";`
but I get:
`import { Test } from "../testtest";`

So the Path gets lowercased when I use QuickFix - in my case this will result in an file-not-found error on my server.
It would be awesome if someone could help!

Thanks for your Time, and I love this piece of software!

~nerothe

**Comment by basarat** [comment]
I've experience that as well. Its resulted in a few of my builds breaking because of my commits. Raised here as this one is coming from Microsoft/TypeScript proper : https://github.com/Microsoft/TypeScript/issues/13339 :rose:

**Comment by basarat** [comment]
Tracked upstream : https://github.com/Microsoft/TypeScript/issues/13109 :rose:
