### ISSUE TITLE
Link ‘ Now head on to the Docs ’ is broken

### ISSUE THREAD

**Issue by MNF** [alm-tools/alm-tools.github.io#6]
On  http://alm.tools/ Link   Now head on to the Docs http://alm.tools/alm-tools_subdomain/-gitbooks-io/alm/content/ is broken

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: alm-tools_subdomain/-gitbooks-io/alm/content/index.html
RequestId: B72961B5BAF8FA11
HostId: kqHV5gnvzxHLRldzw1dDDWZumJF5kdiUu4470cqSrg6pVQHpdRU++mF1L6gzUW9amkw/BJo8oHU=

**Comment by basarat** [comment]
Project is archived so I didn't update (pay) `http://alm.tools/` but scammers took it 😢 
Correct link is http://alm-tools.github.io/ provided for free by github :rose:
